# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_designation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorSectionPeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=100, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.IndicatorSectionPeriode')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_designation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='involvedpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Partner'),
        ),
        migrations.AddField(
            model_name='indicatorsectionperiode',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Output'),
        ),
        migrations.AddField(
            model_name='indicatorsectionperiode',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Periode'),
        ),
        migrations.AddField(
            model_name='indicatorsectionperiode',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Section'),
        ),
        migrations.AddField(
            model_name='concernedreport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.IndicatorSectionPeriode'),
        ),
        migrations.AddField(
            model_name='concernedreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indicators_app.Report'),
        ),
    ]
