# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicators_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='output_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
