# Generated by Django 2.2 on 2019-04-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Indicators_app', '0002_output_output_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concernedreport',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='indicatorsectionperiode',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='involvedpartner',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='periode',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='concernedreport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernedreports', to='Indicators_app.IndicatorSectionPeriode'),
        ),
        migrations.AlterField(
            model_name='concernedreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernedreports', to='Indicators_app.Report'),
        ),
        migrations.AlterField(
            model_name='indicatorsectionperiode',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatorsectionperiodes', to='Indicators_app.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorsectionperiode',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatorsectionperiodes', to='Indicators_app.Output'),
        ),
        migrations.AlterField(
            model_name='indicatorsectionperiode',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatorsectionperiodes', to='Indicators_app.Periode'),
        ),
        migrations.AlterField(
            model_name='indicatorsectionperiode',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatorsectionperiodes', to='Indicators_app.Section'),
        ),
        migrations.AlterField(
            model_name='involvedpartner',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvedpartners', to='Indicators_app.IndicatorSectionPeriode'),
        ),
        migrations.AlterField(
            model_name='involvedpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvedpartners', to='Indicators_app.Partner'),
        ),
    ]
